authors:
  adnankaya:
    name: Adnan Kaya
    description: Author
    avatar: https://avatars.githubusercontent.com/u/58748145?v=4
    url: https://adnankaya.github.io
  team:
    name: Team
    description: Author
    avatar: https://simpleicons.org/icons/materialformkdocs.svg
  